apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mystok-ingress
  annotations:
#    kubernetes.io/ingress.global-static-ip-name: mystok-ip
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: mystok-app
          servicePort: 80
