apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoScaler
metadata:
  name: mystok-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mystok-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resouce
    resource:
      name: cpu
      targetAverageUtilization: 50
    behavior
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
        - type: Pods
          value: 1
          periodSeconds: 15
      scaleUp:
        stabilizationWindowSeconds: 0
        policies:
        - type: Pods
          value: 2
          periodSeconds: 15
