apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mystok-proxy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mystok-proxy
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
