name: Apply k8s manifest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   
  apply-k8s-manifest:
    name: Apply k8s manifest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
     
      - name: get gke credentials
        id: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ secrets.gcp_cluster_name }}
          location: ${{ secrets.gcp_location }}
          credentials: ${{ secrets.gcp_credentials }}
          
      - name: Create service account secret
        continue-on-error: true
        run: kubectl create secret generic gcp-sa-mystok-secret --from-literal=service_account.json=\
          '${{ secrets.gcp_sa_credentials }}'

# The KUBECONFIG env var is automatically exported and picked up by kubectl.
      - name: Run shell script
        id: get-pods
        run: ./mystok-k8s-start.sh

      - name: update mystok images
        run: |
          kubectl rollout restart deploy mystok-db
          kubectl rollout restart deploy mystok-app
          kubectl rollout restart deploy mystok-proxy
