name: Apply k8s manifest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   
  apply-k8s-manifest:
    name: Apply k8s manifest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
     
      - name: get gke credentials
        id: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ secrets.gcp_cluster_name }}
          location: ${{ secrets.gcp_location }}
          credentials: ${{ secrets.gcp_credentials }}

      - name: Decrypt gcp_sa_key.json.gpg
        run: ./.github/scripts/decrypt_secret.sh
        env:
          GCP_SA_PASSPHRASE: ${{ secrets.GCP_SA_PASSPHRASE }}

      - name: Decrypt mystok-cloudstorage-sa-key.json.gpg 
        run: ./.github/scripts/decrypt_secret-cloud-storage.sh
        env:
          MYSTOK-CLOUDSTORAGE-SA-PASSPHRASE: ${{ secrets.MYSTOK-CLOUDSTORAGE-SA-PASSPHRASE }}
          
      - name: Create GCP SA secret
        continue-on-error: true
        run: kubectl create secret generic gcp-sa-mystok-secret --from-file=service_account.json=$HOME/secrets/gcp_sa_key.json

      - name: Create Cloud Storage SA secret
        continue-on-error: true
        run: kubectl create secret generic mystok-cloud-storage-sa-secret --from-file=key.json=$HOME/secrets/mystok-cloudstorage-sa-key.json

# The KUBECONFIG env var is automatically exported and picked up by kubectl.
      - name: Run shell script
        id: get-pods
        run: ./.github/scripts/mystok-k8s-start.sh

#      - name: update mystok images
#        run: |
#          kubectl rollout restart deploy mystok-app
#          kubectl rollout restart deploy mystok-proxy
